=== RyanOatz99/terraform-google-foundation-network/schemas/networks.schema.json
{
    "$id": "networks.schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Networks",
    "type": "array",
    "items": {
        "title": "Network",
        "description": "A Virtual Private Cloud (VPC) network implemented inside of Google's production network",
        "type": "object",
        "additionalProperties": false,
        "required": [
            "name"
        ],
        "properties": {
            "name": {
                "title": "Name",
                "description": "This field will be used be combine with [environment] and [prefix] to generate a unique VPC name",
                "type": "string",
                "examples": [
                    {
                        "name": "alpha",
                        "subnetworks": "......",
                        "routes": "......",
                        "firewall_rules": "....."
                    },
                    {
                        "name": "bravo",
                        "subnetworks": "......",
                        "routes": "......",
                        "firewall_rules": "....."
                    }
                ]
            },
            "description": {
                "title": "Description",
                "description": "Description to be used for the created Network",
                "type": "string"
            },
            "mtu": {
                "title": "MTU",
                "description": "Maximum transmission unit (MTU) is the size of the largest IP packet that can be transmitted on this network.",
                "type": "number",
                "enum": [
                    1460,
                    1500
                ],
                "default": 1460,
                "examples": [
                    [
                        {
                            "name": "......",
                            "mtu": 1460,
                            "subnetworks": "......",
                            "routes": "......",
                            "firewall_rules": "....."
                        },
                        {
                            "name": "......",
                            "mtu": 1500,
                            "subnetworks": "......",
                            "routes": "......",
                            "firewall_rules": "....."
                        }
                    ]
                ]
            },
            "private_google_access": {
                "title": "Private Google Access",
                "description": "Private Google Access for is an alternative to connecting to Google APIs and services over the internet. Setting this to PRIVATE or RESTRICTED will deploy the required Cloud DNS and Routing functionality to enable this feature.",
                "type": "string",
                "oneOf": [
                    {
                        "title": "Disabled",
                        "description": "Does not depl",
                        "const": "DISABLED"
                    },
                    {
                        "title": "Private",
                        "description": "Enables API access to most Google APIs and services regardless of whether they are supported by VPC Service Controls.",
                        "const": "PRIVATE"
                    },
                    {
                        "title": "Restricted",
                        "description": "Provides access to Cloud and Developer APIs that support VPC Service Controls. Blocks access to Google APIs and services that do not support VPC Service Controls.",
                        "const": "RESTRICTED"
                    }
                ],
                "default": "DISABLED",
                "examples": [
                    [
                        {
                            "name": "......",
                            "private_google_access": "DISABLED",
                            "subnetworks": "......",
                            "routes": "......",
                            "firewall_rules": "....."
                        }
                    ],
                    [
                        {
                            "name": "......",
                            "private_google_access": "PRIVATE",
                            "subnetworks": "......",
                            "routes": "......",
                            "firewall_rules": "....."
                        }
                    ],
                    [
                        {
                            "name": "......",
                            "private_google_access": "RESTRICTED",
                            "subnetworks": "......",
                            "routes": "......",
                            "firewall_rules": "....."
                        }
                    ]
                ]
            },
            "private_service_connection": {
                "title": "Private Service Connection",
                "description": "Allows private consumption of services across VPC networks that belong to different groups, teams, projects, or organizations",
                "oneOf": [
                    {
                        "title": "IP CIDR Range",
                        "type": "object",
                        "properties": {
                            "export_custom_routes": {
                                "title": "Export Custom Routes",
                                "description": "If true, the network will export custom routes to peer network.",
                                "type": "boolean",
                                "default": false
                            },
                            "import_custom_routes": {
                                "title": "Import Custom Routes",
                                "description": "If true, the network will import custom routes from peer network.",
                                "type": "boolean",
                                "default": false
                            },
                            "ip_cidr_range": {
                                "title": "IP CIDR Range",
                                "$ref": "subnetworks.schema.json#/definitions/shared/properties/ip_cidr_range"
                            }
                        },
                        "required": [
                            "ip_cidr_range"
                        ],
                        "examples": [
                            {
                                "ip_cidr_range": "192.168.0.0/24",
                                "export_custom_routes": true,
                                "import_custom_routes": false
                            }
                        ]
                    },
                    {
                        "title": "IP CIDR Prefix",
                        "type": "object",
                        "properties": {
                            "export_custom_routes": {
                                "title": "Export Custom Routes",
                                "description": "If true, the network will export custom routes to peer network.",
                                "type": "boolean",
                                "default": false
                            },
                            "import_custom_routes": {
                                "title": "Import Custom Routes",
                                "description": "If true, the network will import custom routes from peer network.",
                                "type": "boolean",
                                "default": false
                            },
                            "ip_cidr_prefix": {
                                "title": "IP CIDR PRefix",
                                "description": "IP CIDR prefix used for this connection. Google will automtically allocated a IP CIDR Range based on the provided prefix",
                                "type": "integer",
                                "minimum": 8,
                                "maximum": 30,
                                "examples": [
                                    16
                                ]
                            }
                        },
                        "required": [
                            "ip_cidr_prefix"
                        ],
                        "examples": [
                            {
                                "ip_cidr_prefix": "16",
                                "export_custom_routes": true,
                                "import_custom_routes": false
                            }
                        ]
                    }
                ],
                "examples": [
                    [
                        {
                            "name": "......",
                            "private_service_connection": {
                                "ip_cidr_range": "192.168.0.0/24",
                                "export_custom_routes": true,
                                "import_custom_routes": false
                            },
                            "subnetworks": "......",
                            "routes": "......",
                            "firewall_rules": "....."
                        }
                    ],
                    [
                        {
                            "name": "......",
                            "private_service_connection": {
                                "ip_cidr_prefix": "16",
                                "export_custom_routes": true,
                                "import_custom_routes": false
                            },
                            "subnetworks": "......",
                            "routes": "......",
                            "firewall_rules": "....."
                        }
                    ]
                ]
            },
            "routing_mode": {
                "type": "string",
                "title": "Routing Mode",
                "description": "The BGP routing mode for this network. ",
                "oneOf": [
                    {
                        "title": "Global",
                        "description": "Cloud Routers in this network advertise subnetworks from all regions to their BGP peers, and program instances in all regions with the router's best learned BGP routes.",
                        "const": "GLOBAL"
                    },
                    {
                        "title": "Regional",
                        "description": "Cloud Routers in this network advertise subnetworks from their local region only to their BGP peers, and program instances in their local region only with the router's best learned BGP routes. ",
                        "const": "REGIONAL"
                    }
                ],
                "default": "REGIONAL",
                "examples": [
                    [
                        {
                            "name": "......",
                            "routing_mode": "REGIONAL",
                            "subnetworks": "......",
                            "routes": "......",
                            "firewall_rules": "....."
                        }
                    ],
                    [
                        {
                            "name": "......",
                            "routing_mode": "GLOBAL",
                            "subnetworks": "......",
                            "routes": "......",
                            "firewall_rules": "....."
                        }
                    ]
                ]
            },
            "subnetworks": {
                "title": "Subnetworks",
                "$ref": "subnetworks.schema.json#/definitions/subnetworks"
            },
            "cloud_nat": {
                "title": "Cloud NAT",
                "$ref": "cloud_nat.schema.json#/definitions/cloud_nat"
            },
            "peers": {
                "title": "VPC Network Peers",
                "description": "Collection of VPC Peers that enables you to connect VPC networks so that workloads in different VPC networks can communicate internally.",
                "type": "array",
                "uniqueItems": true,
                "items": {
                    "title": "VPC Network Peer",
                    "type": "object",
                    "properties": {
                        "project": {
                            "title": "Project",
                            "description": "The name of the project for the peer network. If not specified, defaults to current project.",
                            "type": "string",
                            "examples": [
                                "remote-project-id"
                            ]
                        },
                        "network": {
                            "title": "Peer Network",
                            "description": "The name of the network to be peered with the current network.",
                            "type": "string",
                            "examples": [
                                "prod-network"
                            ]
                        },
                        "export_custom_routes": {
                            "title": "Export Custom Routes",
                            "description": "If true, the network will export custom routes to peer network.",
                            "type": "boolean",
                            "default": false
                        },
                        "import_custom_routes": {
                            "title": "Import Custom Routes",
                            "description": "If true, the network will import custom routes from peer network.",
                            "type": "boolean",
                            "default": false
                        },
                        "import_subnet_routes_with_public_ip": {
                            "title": "Import Subnet Routes with Public IP Addresses",
                            "description": "If true, the network will import subnet routes with addresses in the public IP ranges from peer network.",
                            "type": "boolean",
                            "default": false
                        },
                        "export_subnet_routes_with_public_ip": {
                            "title": "Export Subnet Routes with Public IP Addresses",
                            "description": "If true, the network will export subnet routes with addresses in the public IP ranges from peer network.",
                            "type": "boolean",
                            "default": false
                        }
                    },
                    "required": [
                        "network"
                    ],
                    "examples": [
                        {
                            "network": "prod-network"
                        },
                        {
                            "network": "dev-network",
                            "export_custom_routes": false,
                            "import_custom_routes": true
                        },
                        {
                            "network": "test-network",
                            "export_custom_routes": false,
                            "import_custom_routes": true,
                            "import_subnet_routes_with_public_ip": false,
                            "export_subnet_routes_with_public_ip": true
                        },
                        {
                            "project": "remote-project-id",
                            "network": "remote-network"
                        }
                    ]
                },
                "examples": [
                    [
                        {
                            "name": "......",
                            "peers": [
                                {
                                    "network": "prod-network"
                                },
                                {
                                    "network": "dev-network",
                                    "export_custom_routes": false,
                                    "import_custom_routes": true
                                },
                                {
                                    "project": "remote-project-id",
                                    "network": "remote-network"
                                }
                            ],
                            "subnetworks": "......",
                            "routes": "......",
                            "firewall_rules": "....."
                        }
                    ]
                ]
            },
            "routes": {
                "title": "Static Routes",
                "$ref": "routes.schema.json#/definitions/routes"
            },
            "firewall_rules": {
                "title": "Firewall Rules",
                "$ref": "firewall_rules.schema.json#/definitions/firewall_rules"
            }
        }
    },
    "examples": [
        [
            {
                "name": "network-single",
                "description": "This will create a single VPC Network and nothing else"
            }
        ],
        [
            {
                "name": "network-alpha",
                "description": "This will create a network alpha and nothing else"
            },
            {
                "name": "network-bravo",
                "description": "This will create a network bravo and nothing else"
            }
        ],
        [
            {
                "name": "subnetwork-secondary-subnetworks",
                "description": "This will create a single VPC Network, Primary Subnetwork and two Secondary Ranges",
                "subnetworks": [
                    {
                        "region": "US-EAST4",
                        "ip_cidr_range": "172.16.0.0/24",
                        "secondary_subnetworks": [
                            {
                                "ip_cidr_range": "172.16.1.0/24"
                            },
                            {
                                "ip_cidr_range": "172.16.2.0/24"
                            }
                        ]
                    }
                ]
            }
        ],
        [
            {
                "name": "cloud-nat-all",
                "description": "This will create a single VPC Network with Primary and Secondary Subnetworks with Cloud-NAT",
                "routing_mode": "GLOBAL",
                "cloud_nat": {
                    "subnetworks_to_nat": "ALL_PRIMARY_SUBNETWORKS_ALL_SECONDARY_SUBNETWORKS"
                },
                "subnetworks": [
                    {
                        "region": "US-WEST1",
                        "ip_cidr_range": "172.16.32.0/24",
                        "secondary_subnetworks": [
                            {
                                "ip_cidr_range": "10.20.32.0/24"
                            },
                            {
                                "ip_cidr_range": "10.20.33.0/24"
                            }
                        ]
                    }
                ]
            }
        ]
    ]
}

=== RyanOatz99/terraform-google-foundation-network/networks/mgmt.json
[
  {
    "name": "mgmt-global",
    "routing_mode": "GLOBAL",
    "description": "",
    "subnetworks": {
      "us-central1": {
        "0": {
          "description": "",
          "purpose": "PRIVATE",
          "ip_cidr_range": "10.255.0.0/24",
          "private_google_access": true,
          "log_config": {
            "aggregation_interval": "INTERVAL_30_SEC",
            "flow_sampling": 1,
            "metadata": "INCLUDE_ALL_METADATA",
            "metadata_fields": []
          },
          "secondary_ranges": []
        }
      },
      "us-east4": {
        "0": {
          "description": "",
          "purpose": "PRIVATE",
          "ip_cidr_range": "10.255.32.0/24",
          "private_google_access": true,
          "log_config": {
            "aggregation_interval": "INTERVAL_30_SEC",
            "flow_sampling": 1,
            "metadata": "INCLUDE_ALL_METADATA",
            "metadata_fields": []
          },
          "secondary_ranges": []
        }
      }
    },
    "firewall_rules": [
      {
        "id": "allow-ssh-rteller",
        "description": "",
        "action": "allow",
        "priority": 1000,
        "direction": "INGRESS",
        "sources": [
          "98.247.221.22/32"
        ],
        "targets": [
          "ngfw"
        ],
        "rules": [
          {
            "protocol": "TCP",
            "ports": [
              22,
              443
            ]
          }
        ]
      }
    ],
    "routes":[
      {
        "name": "mgmt-global-default",
        "dest_range": "0.0.0.0/0",
        "priority": 0,
        "next_hop_gateway": "default-internet-gateway"
      }
    ]
  }
]

=== RyanOatz99/terraform-google-foundation-network/examples/test/networks_dev/inside.json
[
  {
    "name": "inside-use4",
    "routing_mode": "GLOBAL",
    "cloud_nat": {
      "ip_ranges_to_nat": "ALL_SUBNETWORKS_ALL_IP_RANGES"
    },
    "subnetworks": [
      {
        "region": "us-east4",
        "description": "",
        "purpose": "PRIVATE",
        "ip_cidr_range": "172.16.34.0/24",
        "private_ip_google_access": true,
        "log_config": {
          "aggregation_interval": "INTERVAL_30_SEC",
          "flow_sampling": 1,
          "metadata": "INCLUDE_ALL_METADATA",
          "metadata_fields": []
        }
      },
      {
        "region": "us-east4",
        "description": "",
        "purpose": "PRIVATE",
        "ip_cidr_range": "172.16.35.0/24",
        "private_ip_google_access": true,
        "log_config": {
          "aggregation_interval": "INTERVAL_30_SEC",
          "flow_sampling": 1,
          "metadata": "INCLUDE_ALL_METADATA",
          "metadata_fields": []
        }
      }
    ]
  },
  {
    "name": "inside-usc1",
    "routing_mode": "GLOBAL",
    "cloud_nat": {
      "ip_ranges_to_nat": "ALL_SUBNETWORKS_ALL_PRIMARY_IP_RANGES"
    },
    "subnetworks": [
      {
        "region": "us-central1",
        "description": "",
        "purpose": "PRIVATE",
        "ip_cidr_range": "172.16.34.0/24",
        "private_ip_google_access": true,
        "log_config": {
          "aggregation_interval": "INTERVAL_30_SEC",
          "flow_sampling": 1,
          "metadata": "INCLUDE_ALL_METADATA",
          "metadata_fields": []
        },
        "secondary_ranges": []
      }
    ]
  },
  {
    "name": "inside-use1",
    "routing_mode": "GLOBAL",
    "cloud_nat": {
      "ip_ranges_to_nat": "SELECTED_SUBNETWORKS_SELECTED_IP_RANGES"
    },
    "subnetworks": [
      {
        "region": "us-east1",
        "description": "",
        "purpose": "PRIVATE",
        "ip_cidr_range": "172.16.34.0/24",
        "private_ip_google_access": true,
        "ip_ranges_to_nat": "SELECTED_IP_RANGES",
        "cloud_nat_selected": true,        
        "log_config": {
          "aggregation_interval": "INTERVAL_30_SEC",
          "flow_sampling": 1,
          "metadata": "INCLUDE_ALL_METADATA",
          "metadata_fields": []
        },
        "secondary_ranges": [
          {
            "cloud_nat_selected": true,
            "range_name": "testing-secondary-range-alpha",
            "ip_cidr_range": "1.1.1.0/24"
          },
          {
            "cloud_nat_selected": false,
            "range_name": "testing-secondary-range-bravo",
            "ip_cidr_range": "1.1.2.0/24"
          }
        ]
      },
      {
        "region": "us-east1",
        "description": "",
        "purpose": "PRIVATE",
        "ip_cidr_range": "172.16.35.0/24",
        "private_ip_google_access": true,
        "ip_ranges_to_nat": "ALL_IP_RANGES",
        "log_config": {
          "aggregation_interval": "INTERVAL_30_SEC",
          "flow_sampling": 1,
          "metadata": "INCLUDE_ALL_METADATA",
          "metadata_fields": []
        },
        "secondary_ranges": [
          {
            "range_name": "testing-secondary-range-alpha",
            "ip_cidr_range": "2.2.1.0/24"
          },
          {
            "cloud_nat_selected": false,
            "range_name": "testing-secondary-range-bravo",
            "ip_cidr_range": "2.2.2.0/24"
          }
        ]
      }
    ]
  }
]

=== RyanOatz99/terraform-google-foundation-network/networks/dmz.json
[
  {
    "name": "dmz-global",
    "routing_mode": "GLOBAL",
    "description": "",
    "subnetworks": {
      "us-central1": {
        "0": {
          "description": "",
          "purpose": "PRIVATE",
          "ip_cidr_range": "192.168.0.0/24",
          "private_google_access": true,
          "log_config": {
            "aggregation_interval": "INTERVAL_30_SEC",
            "flow_sampling": 1,
            "metadata": "INCLUDE_ALL_METADATA",
            "metadata_fields": []
          },
          "secondary_ranges": [ ]
        },
        "1": {
          "description": "",
          "purpose": "PRIVATE",
          "ip_cidr_range": "192.168.2.0/24",
          "private_google_access": true,
          "log_config": {
            "aggregation_interval": "INTERVAL_30_SEC",
            "flow_sampling": 1,
            "metadata": "INCLUDE_ALL_METADATA",
            "metadata_fields": []
          },
          "secondary_ranges": [ ]
        }
      },  
      "us-east4": {
        "0": {
          "description": "",
          "purpose": "PRIVATE",
          "ip_cidr_range": "192.168.32.0/24",
          "private_google_access": true,
          "log_config": {
            "aggregation_interval": "INTERVAL_30_SEC",
            "flow_sampling": 1,
            "metadata": "INCLUDE_ALL_METADATA",
            "metadata_fields": []
          },
          "secondary_ranges": [ ]
        },
        "1": {
          "description": "",
          "purpose": "PRIVATE",
          "ip_cidr_range": "192.168.34.0/24",
          "private_google_access": true,
          "log_config": {
            "aggregation_interval": "INTERVAL_30_SEC",
            "flow_sampling": 1,
            "metadata": "INCLUDE_ALL_METADATA",
            "metadata_fields": []
          },
          "secondary_ranges": [ ]
        }
      }
    },
    "firewall_rules":[],
    "routes":[]
  }
]
